### ISSUE TITLE
如何把 ipdb 转换成 txt 格式

### ISSUE THREAD

**Issue by lsn113756** [metowolf/ipdb#2]
如何把 ipdb 转换成 txt 格式 大佬 求教程

**Comment by metowolf** [comment]
需要用到 ipdb 和 @ipdb/range
一个简单的 demo 如下

```
const IPDB = require('ipdb');
const ipdb_range = require('@ipdb/range');
const ipdb = new IPDB('./ipipfree.ipdb', {
  patches: [ipdb_range]
});

let ip = '0.0.0.0';
while (true) {
  let info = ipdb.find(ip);
  console.log([
    info.data.range.from,
    info.data.range.to,
    info.data.country_name,
    info.data.region_name,
    info.data.city_name
  ].join('\t'))
  ip = info.data.range.next

  if (ip === '0.0.0.0') break;
}
```

**Comment by lsn113756** [comment]
Thank you very much.


------------------ 原始邮件 ------------------
发件人: "METO"<notifications@github.com>;
发送时间: 2019年6月12日(星期三) 晚上7:13
收件人: "metowolf/ipdb"<ipdb@noreply.github.com>;
抄送: "么么"<1009386198@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [metowolf/ipdb] 如何把 ipdb 转换成 txt 格式 (#2)




需要用到 ipdb 和 @ipdb/range
 一个简单的 demo 如下
 const IPDB = require('ipdb'); const ipdb_range = require('@ipdb/range'); const ipdb = new IPDB('./ipipfree.ipdb', {   patches: [ipdb_range] }); let ip = '0.0.0.0'; while (true) {   let info = ipdb.find(ip);   console.log([     info.data.range.from,     info.data.range.to,     info.data.country_name,     info.data.region_name,     info.data.city_name   ].join('\t'))   ip = info.data.range.next   if (ip === '0.0.0.0') break; }
